Generation 모듈 작업
prography/pg-homepage-backend pull request #10
Opened 2022-10-19 10:07 UTC by Linho1150

Close #8 

## 작업내용
Generation CRUD 작업 완료했습니다!

## 주의사항
Feature/9 ( All-Exception )와 함께 사용 되는 코드가 있어서 둘다 머지 해야 정상적으로 구동됩니다 :)
중간에 Github Commit을 기능별로 안해놨는데, 다음번 커밋부턴 기능별로 하겠습니다~

2022-10-19 12:14 UTC, be-student requested changes

2022-10-19 12:14 UTC, be-student commented on src/modules/generation/service/generation.service.ts
> +    return await this.generationRepository.find();
repository 에 메서드를 정의하지 않으면 repository를 사용할 의미가 있을지 궁금합니다

2022-10-19 12:15 UTC, be-student commented on src/modules/generation/service/generation.service.ts
> +    return await this.generationRepository.find();
repository 안에 find method를 정의하는 방법을 사용하거나, repository를 만들어야 하는 이유를 적어주시면 감사하겠습니다

2022-10-19 12:20 UTC, Linho1150 commented on src/modules/generation/service/generation.service.ts
> +    return await this.generationRepository.find();
당장 repository 파일에는 내용이 없으나, 차후 QueryBuilder를 사용할 경우를 고려하여 세팅해 놓았습니다.
QueryBuilder를 사용할 경우 repository.ts에 메소드를 정의하여 사용할 계획입니다.

2022-10-19 12:52 UTC, be-student commented
추가적으로 고민해보면 좋을 부분 : 과연 service에서 controller로 entity를 내보내는게 맞을지?
entity가 아니라 dto를 통해서 진행해야 하지 않을까요

2022-10-19 12:52 UTC, be-student requested changes

2022-10-21 07:27 UTC, Linho1150 commented on src/modules/generation/service/generation.service.ts
> +    return await this.generationRepository.find();
@be-student Service와 Repository 분리하여 수정하였습니다 ;)

2022-10-21 07:29 UTC, Linho1150 commented
> 추가적으로 고민해보면 좋을 부분 : 과연 service에서 controller로 entity를 내보내는게 맞을지? entity가 아니라 dto를 통해서 진행해야 하지 않을까요

2022-10-21 07:31 UTC, Linho1150 commented on src/modules/generation/controller/generation.controller.ts
> +      throw new HttpException('없는 기수입니다.', HttpStatus.NOT_FOUND);
@be-student 해당부분은 Exception 과정을 따로 PR하다가 실수로 처리하지 못한 부분이 있어서 다음 PR에 반영하겠습니다

2022-10-21 07:31 UTC, Linho1150 commented on src/modules/generation/controller/generation.controller.ts
> +  @ApiNotFoundResponse({ description: '해당 기수가 없음', type: ErrorDto })
@be-student 변경했습니다 ;)

2022-10-22 08:42 UTC, be-student approved these changes

2022-10-22 12:42 UTC, merged